### ISSUE TITLE
Sparkline request: CORS error

### ISSUE THREAD

**Issue by ryan2625** [ryan2625/crypto-net#27]
Sparkline data fetched from coingecko has headers set to strict origin policy. Route the api request through the backend and change the CORS header. This is a breaking issue in the trending page. Fix ASAP.

**Comment by ryan2625** [comment]
Serve images... download images from readable node stream. Host externally or use cors proxy reverse from Heroku.

**Comment by Westbrook1000** [comment]
Or convert images to base64 first, different SRC.

**Comment by ryan2625** [comment]
CORS issue can't be resolved... I can't even download their SVGs and create my own image out of it. 403 Error forbidden. I gave up and manually uploaded them to the app.
